Contact preferences
hmrc/sca-change-of-circumstances-frontend pull request #104
Opened 2023-05-26 11:58 UTC by airudah2000

2023-06-09 08:18 UTC, owen-opencast requested changes

2023-06-09 08:18 UTC, owen-opencast commented on app/controllers/IndexController.scala
> +  private def getContactPreferencesRow(implicit request: DataRequest[_], messages: Messages): Future[Option[SummaryListRow]] = {
Could this be moved to a helper class, similar to ManageTaxAgentSummary.row or TrustedHelpersSummary.row?

2023-06-09 08:18 UTC, owen-opencast commented on app/config/FrontendAppConfig.scala
> +  val profileAndSettingsUrl                     = s"$host/personal-account/profile-and-settings"
I think this is getting used to redirect back to our page? In which case the URL would be $host/hmrc-account/update-your-details

2023-06-09 08:26 UTC, owen-opencast reviewed
The unit tests need updating to pass - they shouldn't have any reliance on the stub, the stub should only be getting used in integration tests, ui tests and environments.

When unit testing we tend to mock components outside of the specific component we're testing using Mockito. So when testing the IndexController I'd mock the PreferencesConnector, and test that the correct output is rendered when certain responses are returned from preferences.

CitizenDetails is mocked in a similar manner, eg:

`val mockCitizenDetailsConnector: CitizenDetailsConnector = mock[CitizenDetailsConnector]`
`val application = applicationBuilder(userData = Some(populatedUserData), userAnswers = Some(emptyUserAnswers))
        .configure("features.sca-wrapper-enabled" -> false)
        .overrides(
         ....
          bind[CitizenDetailsConnector].toInstance(mockCitizenDetailsConnector)
        )
        .build()`

and 

`when(mockCitizenDetailsConnector.getPersonalDetails(any())(any()))
          .thenReturn(Future.successful(citizenDetailsResponseWithNoRlsFlags))`

If you need help with the tests, Ned or Christo should be able to help

2023-06-09 10:04 UTC, airudah2000 commented on app/config/FrontendAppConfig.scala
> +  val profileAndSettingsUrl                     = s"$host/personal-account/profile-and-settings"
Fixed

2023-06-09 10:04 UTC, airudah2000 commented on app/connectors/HttpClientResponse.scala
> +class HttpClientResponse @Inject()(implicit ec: ExecutionContext) extends Logging {
Deleted

2023-06-09 10:04 UTC, airudah2000 commented on conf/application.conf
> +play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
Yes. Will remove

2023-06-09 11:03 UTC, airudah2000 commented on app/controllers/IndexController.scala
> +  private def getContactPreferencesRow(implicit request: DataRequest[_], messages: Messages): Future[Option[SummaryListRow]] = {
Will do

2023-06-09 14:22 UTC, airudah2000 commented on test/controllers/IndexControllerWithoutScaWrapperLibrarySpec.scala
>            "must only display certain details (name, nino, main address, postal address)" in {
Done.

2023-06-13 07:21 UTC, owen-opencast reviewed
Looks good, I spotted what looks like typo, but ready otherwise!

2023-06-13 07:21 UTC, owen-opencast commented on app/config/FrontendAppConfig.scala
> +  lazy val pertaxFrontendPaperlessUrl                   = s"$pertaxFrontend/paperless/check-settings?"
Is the '?' a the end of here correct?

2023-06-13 08:24 UTC, airudah2000 commented on app/config/FrontendAppConfig.scala
> +  lazy val pertaxFrontendPaperlessUrl                   = s"$pertaxFrontend/paperless/check-settings?"
No. I've removed it

2023-06-13 08:46 UTC, owen-opencast approved these changes

2023-06-13 12:05 UTC, merged