SCC-1275 | Welsh Language Toggle on the Confirmation page
hmrc/sca-change-of-circumstances-frontend pull request #108
Opened 2023-05-31 15:41 UTC by Neozxc

2023-05-31 23:25 UTC, airudah2000 submitted a review, later dismissed

2023-06-01 07:40 UTC, owen-opencast requested changes
Breaks logic 🙂

2023-06-06 10:25 UTC, owen-opencast reviewed
Looks good - could you add a few tests for the logic around what content is displayed? If nothing was failing when it was incorrect, we have a gap in our testing 🙂

2023-06-07 06:42 UTC, owen-opencast approved these changes

2023-06-07 09:00 UTC, merged