SCC-1318 | agent-client-auth 404s
hmrc/sca-change-of-circumstances-frontend pull request #122
Opened 2023-06-20 13:36 UTC by Neozxc

2023-06-21 13:34 UTC, owen-opencast requested changes

2023-06-21 13:34 UTC, owen-opencast commented on app/controllers/actions/AgentClientRedirectAction.scala
> +    } yield (request.uri.contains(config.manageTaxAgentsUrl), hasAgent) match {
I think here we just need to yield the result - either true or false, including false if there's been an error.

2023-06-21 13:34 UTC, owen-opencast commented on app/controllers/actions/AgentClientRedirectAction.scala
> +    } yield (request.uri.contains(config.manageTaxAgentsUrl), hasAgent) match {
Move this logic to getSettingsSummary

2023-06-21 13:34 UTC, owen-opencast commented on app/controllers/IndexController.scala
> +  def onPageLoad: Action[AnyContent] = (identify andThen getData andThen requireData andThen agentClientCheck).async { implicit request =>
Remove action

2023-06-21 13:34 UTC, owen-opencast commented on app/controllers/IndexController.scala
> +  def onPageLoad: Action[AnyContent] = (identify andThen getData andThen requireData andThen agentClientCheck).async { implicit request =>
Remove call to agentClientAuthService on line 79

2023-06-22 10:40 UTC, ccatosdevelopment submitted a review, later dismissed

2023-06-23 12:46 UTC, owen-opencast approved these changes

2023-06-26 08:27 UTC, merged