SCC-1306 | BUG - "Check Your Details"
hmrc/sca-change-of-circumstances-frontend pull request #128
Opened 2023-06-29 06:29 UTC by Neozxc

2023-06-29 10:25 UTC, ccatosdevelopment approved these changes

2023-06-29 13:16 UTC, owen-opencast requested changes

2023-06-29 13:16 UTC, owen-opencast commented on app/pages/answers/changeaddress/RemovePostalAddressPage.scala
> +    (value, userAnswers.get(RemovePostalAddressPage)) match {
If you've answered Somewhere else, then click "change", then click submit without changing the answer, the data is wiped and the user must complete the journey again. Instead, the user to return to Check Your Answers.

cleanup is run _after_ the value is set in user answers, so userAnswers.get(RemovePostalAddressPage) will always match Some(_). Have a look at IsNewAddressInUkPage - the way to do it is to figure out the users previous answer with other answers...

- If they've previously answered "Main", there should be no further answers... i.e. EnterYourUkAddressPage should return None.
- If they've previously answered "Somewhere else", then there should be an answer somewhere. 

You could maybe check with !AddressJourney.hasAnsweredUk && !AddressJourney.hasAnsweredInternational - i.e. no answers = main.

2023-07-31 15:52 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2023-08-07 17:10 UTC, owen-opencast approved these changes

2023-08-07 17:10 UTC, owen-opencast commented on app/pages/answers/changeaddress/RemovePostalAddressPage.scala
> +            .flatMap(_.remove(WhatIsYourNewAddressNonUkPage))
Think we also need a WhenDidYouStartLivingHere wiped here

2023-08-08 10:33 UTC, owen-opencast approved these changes

2023-08-08 11:03 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2023-08-08 12:34 UTC, merged