changed to match regex pattern for post code with the backend regex p…
hmrc/sca-change-of-circumstances-frontend pull request #161
Opened 2023-08-17 08:51 UTC by kritikarai6

…attern

2023-08-17 17:28 UTC, owen-opencast requested changes

2023-08-17 17:28 UTC, owen-opencast commented on app/forms/mappings/FormHelper.scala
> +    "^[A-Z]{1,2}[0-9][0-9A-Z]?\\s?[0-9][A-Z]{2}|BFPO\\s?[0-9]{1,10}$"
I noticed that the previous PTA regex allows lower case characters to be entered, but the new NPS regex doesn't. We don't want to fail users for having entered lower case letters - I wonder whether this was causing some of our issues? Could we change the NPS regex here to allow lowercase, and then make sure we transform to uppercase after input so we don't fail validation at the back end?

2023-08-18 14:11 UTC, kritikarai6 commented on app/forms/mappings/FormHelper.scala
> +    "^[A-Z]{1,2}[0-9][0-9A-Z]?\\s?[0-9][A-Z]{2}|BFPO\\s?[0-9]{1,10}$"
change made to convert upper case to lower case

2023-08-18 15:00 UTC, owen-opencast approved these changes

2023-08-18 15:26 UTC, merged