SO-43 | Logic & Content for Same/Earlier Start Date Error Page
hmrc/sca-change-of-circumstances-frontend pull request #187
Opened 2023-10-20 12:30 UTC by ccatosdevelopment

Edit: since this PR was last reviewed, `FallbackDate` has been implemented, including corresponding tests, to handle the instance where the start date for the user's previous address cannot be found.

----

_Note: depending on when other tickets currently being reviewed are merged in, there may be merge conflicts to resolve on this ticket (and/or others) which I will resolve as and when they appear._

As the UK/non-UK content displayed in `YourAddressCannotBeUpdatedView` depends only on whether the new address is in the UK or not, the variable `movingFromUk` is redundant and has been removed as part of this ticket.

The `DateBeforeNPS` Boolean that was used to determine what content to display in `YourAddressCannotBeUpdatedView` has been replaced by the new `DateComparison`, in order for the logic to cater for 3 different kinds of date errors (future/same/earlier), where there used to be only 2 (future/earlier).

No changes were made to the content in `YourAddressCannotBeUpdatedView` for either of the `FutureDate` cases, as that work is captured in a separate ticket. Some minor formatting changes were made in these cases, to make the formatting more consistent.

Similarly, no changes were made to the tests within `YourAddressCannotBeUpdatedControllerSpec` that are testing the content for any of the 4 `FutureDate` cases, as that work is captured in a separate ticket. The only changes made in these 4 test cases were formatting changes and necessary 'knock-on' changes that came about from the `YourAddressCannotBeUpdatedView` parameters and test data changing.

Lastly, the changes to `YourAddressCannotBeUpdatedControllerSpec` may look daunting, but the bulk of each test case is identical to the others, and many of the changes are simply formatting/re-ordering, with few changes to the previous tests themselves, besides the 3 `document.select(govukBodySelector)...` blocks of code that have been added to the end of each of the `SameDate` & `EarlierDate` test cases.

2023-10-23 14:34 UTC, kritikarai6 submitted a review, later dismissed

2023-10-31 16:46 UTC, owen-opencast requested changes

2023-10-31 16:46 UTC, owen-opencast commented on app/controllers/changeaddress/YourAddressCannotBeUpdatedController.scala
> +            val fallbackDate = LocalDate.of(1,1,1)
I think this can be refactored to remove the fallbackDate constant if we map from the oldAddress.startDate Option to a DateComparison with a .getOrElse supplying FallbackDate

2023-10-31 16:46 UTC, owen-opencast commented on app/controllers/changeaddress/YourAddressCannotBeUpdatedController.scala
> +                s"$dateComparison, $movingToInternational, ${request2session.get("sessionId").getOrElse("-")}"
Keep the original logging (dateBeforeNPS boolean, movingFromUk boolean)

2023-10-31 16:46 UTC, owen-opencast commented on app/views/changeaddress/YourAddressCannotBeUpdatedView.scala.html
> +            case (FutureDate, false) => {
I think this can be simplified a bit. I think the top two `.govuk-body` are there in every case - can you do a match within each just varying the message? I think it'll make it easier to read if there's a fixed structure within which things vary, rather than specifying every combination

2023-11-01 08:47 UTC, ccatosdevelopment commented on app/controllers/changeaddress/YourAddressCannotBeUpdatedController.scala
> +                s"$dateComparison, $movingToInternational, ${request2session.get("sessionId").getOrElse("-")}"
I've reverted to the logging from the original implementation, but I've renamed `dateBeforeNPS` to `dateSameOrEarlierThanNPS`, as the original implementation returns `true` when the date is the same.

2023-11-01 15:50 UTC, ccatosdevelopment commented on app/views/changeaddress/YourAddressCannotBeUpdatedView.scala.html
> +            case (FutureDate, false) => {
Thanks for the tip, I've refactored the View accordingly and it's much easier to read now! Since this ticket only concerns the content for the `SameDate` and `EarlierDate` cases, I've left the content for the `FutureDate` cases as is. This results in some slightly unusual match expressions, but it's worth noting that these will be updated/removed accordingly when the `FutureDate` content update ticket is written up and carried out. It currently looks like the updated `FutureDate` content will remove the need for a match expression for 'Line 2' altogether, and will simplify the match expression for 'Line 3'.

2023-11-03 11:42 UTC, owen-opencast submitted a review, later dismissed

2023-11-08 10:45 UTC, owen-opencast approved these changes

2023-11-08 11:51 UTC, merged