Scc 915
hmrc/sca-change-of-circumstances-frontend pull request #44
Opened 2023-01-03 11:09 UTC by ccatosdevelopment

2023-01-03 16:33 UTC, owen-opencast requested changes

2023-01-03 16:33 UTC, owen-opencast commented on app/views/changeaddress/WhenDidYouStartLivingHereView.scala.html
> +            <h1 class="govuk-fieldset__heading">@(messages("whenDidYouStartLivingHere.heading") + " " + address.take(address.indexOf('<')) + "?")</h1>
Can simplify this by just passing in the first line of address from controller

2023-01-04 13:58 UTC, owen-opencast approved these changes

2023-01-05 10:05 UTC, singh1411gaurav approved these changes

2023-01-05 10:09 UTC, merged