SCC-1075 | Update Main Address - Future Date Error Message
hmrc/sca-change-of-circumstances-frontend pull request #68
Opened 2023-02-27 10:49 UTC by Neozxc

2023-02-27 13:28 UTC, owen-opencast requested changes

2023-02-27 13:28 UTC, owen-opencast commented on test/pages/changeofaddress/FutureDateErrorPageSpec.scala
> +class FutureDateErrorPageSpec extends PageBehaviours {
Redundant

2023-02-27 16:56 UTC, ccatosdevelopment commented on app/pages/answers/changeaddress/FutureDateErrorPage.scala
> +case object FutureDateErrorPage extends QuestionPage[Address] {
File deleted

2023-02-27 16:57 UTC, ccatosdevelopment commented on conf/address.routes
> +GET        /:addressType/future-date-error                                    controllers.changeaddress.FutureDateErrorController.onPageLoad(mode: Mode = NormalMode, addressType: AddressType)
Route updated as suggested, plus related files renamed to match

2023-02-27 16:58 UTC, ccatosdevelopment commented on test-utils/generators/PageGenerators.scala
> +  implicit lazy val arbitraryFutureDateErrorPage: Arbitrary[FutureDateErrorPage.type] =
Deleted

2023-02-27 16:58 UTC, ccatosdevelopment commented on test-utils/generators/UserAnswersEntryGenerators.scala
> +  implicit lazy val arbitraryFutureDateErrorUserAnswersEntry: Arbitrary[(FutureDateErrorPage.type, JsValue)] =
Deleted

2023-02-27 16:58 UTC, ccatosdevelopment commented on test-utils/generators/UserAnswersGenerator.scala
> +    arbitrary[(FutureDateErrorPage.type, JsValue)] ::
Deleted

2023-02-27 16:58 UTC, ccatosdevelopment commented on test/pages/changeofaddress/FutureDateErrorPageSpec.scala
> +class FutureDateErrorPageSpec extends PageBehaviours {
Deleted

2023-02-27 18:18 UTC, owen-opencast requested changes

2023-02-27 18:18 UTC, owen-opencast commented on test/controllers/changeaddress/YourAddressCannotBeUpdatedControllerSpec.scala
> +  val mockService: ChocsService              = mock[ChocsService]
These mocks don't get passed in to the applicationBuilder - can they be removed?

2023-02-28 11:12 UTC, owen-opencast approved these changes

2023-02-28 16:55 UTC, merged