SCC-1134 | Returned Letter Service - Creating New Pages
hmrc/sca-change-of-circumstances-frontend pull request #89
Opened 2023-04-28 09:44 UTC by ccatosdevelopment

2023-05-02 07:47 UTC, owen-opencast requested changes

2023-05-02 07:47 UTC, owen-opencast commented on app/queries/CitizenDetailsQuery.scala
> +case object CitizenDetailsQuery extends Gettable[CitizenDetailsResponse] with Settable[CitizenDetailsResponse] {
I don't this is getting used at the moment? And I don't think we need it... data retrieved from CitizenDetailsConnector is stored as a PersonalDetailsResponse using a PersonalDetailsQuery.

2023-05-02 07:47 UTC, owen-opencast commented on app/pages/data/RlsInterruptPage.scala
> +case object RlsInterruptPage extends QuestionPage[CitizenDetailsResponse] {
Don't need this, we're not storing user data on this page

2023-05-02 07:47 UTC, owen-opencast commented on app/viewmodels/checkAnswers/RlsInterruptPostalSummary.scala
> +       |<div class="govuk-summary-list__row">
Is it possible to implement this as a component, rather than hard coding the HTML? Something like SummaryListRowViewModel from the Index page, or the check your answers? There are a few instances where we've used HTML, but that's usually when the component needs customising, such as adding "CHANGED"  or address locks

2023-05-02 07:47 UTC, owen-opencast commented on conf/app.routes
> +GET         /update-your-address                         controllers.RlsInterruptController.onPageLoad(mainRlsFlag: Boolean, postalRlsFlag: Boolean)
I'm just getting a 400 Bad Request when I try to access this page? http://localhost:10600/single-customer-account/your-details/update-your-address

2023-05-02 07:47 UTC, owen-opencast commented on app/controllers/RlsInterruptController.scala
> +  def onPageLoad(mainRlsFlag: Boolean, postalRlsFlag: Boolean): Action[AnyContent] =
I don't think we want to pass in these as parameters? We'd want to retrieve them from userData on the request using a PersonalDetailsQuery

2023-05-02 09:43 UTC, ccatosdevelopment commented on app/viewmodels/checkAnswers/RlsInterruptPostalSummary.scala
> +       |<div class="govuk-summary-list__row">
The short answer is no - I originally implemented this using SummaryListRowViewModels, but there doesn't seem to be any way to make this match the design for the postal RLS row, because of the two links in the third column. I tried passing in a Seq[ActionItemViewModels], but this creates a vertical divider in the third column and throws off the formatting. I also tried making an extra/third row with a blank first column, but that creates a grey divider between the two rows. So the only way I could implement this in a way that matched the design is to hardcode the HTML.

2023-05-02 10:54 UTC, ccatosdevelopment commented on app/pages/data/RlsInterruptPage.scala
> +case object RlsInterruptPage extends QuestionPage[CitizenDetailsResponse] {
Removed

2023-05-03 14:11 UTC, ccatosdevelopment commented on app/queries/CitizenDetailsQuery.scala
> +case object CitizenDetailsQuery extends Gettable[CitizenDetailsResponse] with Settable[CitizenDetailsResponse] {
Removed

2023-05-04 16:49 UTC, owen-opencast approved these changes

2023-05-04 17:24 UTC, owen-opencast approved these changes

2023-05-04 17:24 UTC, merged