SCC-1177 | Your Details - URL and Audit Event changes for A/B Testing
hmrc/sca-change-of-circumstances-frontend pull request #97
Opened 2023-05-17 15:33 UTC by Neozxc

2023-05-17 15:47 UTC, Neozxc commented on conf/application.conf
>    singleCustomerAccount {
Just realised, do we need to change this? It's touching another port 👀

2023-05-17 15:49 UTC, Neozxc commented on conf/application.conf
> +    taxesAndBenefits = "http://localhost:8420/personal-account/taxes-and-benefits"
Just realised, do we need to change this? It's touching another port 👀

2023-05-18 06:36 UTC, owen-opencast requested changes

2023-05-18 06:36 UTC, owen-opencast commented on conf/application.conf
> +    taxesAndBenefits = "http://localhost:8420/personal-account/taxes-and-benefits"
These are the SCA links in the non-ptaMode menu - revert them

2023-05-30 10:29 UTC, owen-opencast approved these changes

2023-05-30 11:40 UTC, merged