Address Lines Update
hmrc/sca-change-of-circumstances-frontend pull request #99
Opened 2023-05-19 02:03 UTC by airudah2000

2023-05-19 16:20 UTC, owen-opencast requested changes

2023-05-19 16:20 UTC, owen-opencast commented on conf/messages.cy
> +whatIsYourNewAddressNonUk.line4 = Tref neu ddinas
Could we add the welsh for optional on line 4, for consistency (I think lines were translated before line4 was made optional).

2023-05-19 16:56 UTC, airudah2000 commented on conf/messages.cy
> +whatIsYourNewAddressNonUk.line4 = Tref neu ddinas
Will do

2023-05-22 14:48 UTC, owen-opencast approved these changes

2023-05-22 14:51 UTC, merged